### ISSUE TITLE
开发环境没有问题，生产环境跑不起来。。。

### ISSUE THREAD

**Issue by lzq920** [baisheng/nuxt-thinkjs3#3]
RT

**Comment by baisheng** [comment]
生产环境你怎么配置的?
当部署到生产环境后，一定要检查nuxt.config.js中
```javascript
module.exports = {
  dev: process.env.NODE_ENV !== 'production',
  srcDir: 'client/',
  buildDir: '.build/',
```
首先 dev 必需是 true 的状态，其次 .build 中含有 nuxt build 之后的文件，这样在运行中 nuxt 才能找到已 build 完成的内容。
可以参考这个完整的项目，https://github.com/baisheng/podcast-app-manager

**Comment by lzq920** [comment]
是这样的，我的.build/dist目录已经生成了，然后我直接运行node production.js，然后打开浏览器访问不到。

**Comment by baisheng** [comment]
@lzq920 
检查 nuxt.config.js dev 状态是否为 true，发布 production 状态时可以后动设置测试。也可以参考我提供的完整项目，这些都是生产环境中正式运行的项目。
